import {
  CompanySetting,
  InvoiceSetting,
  User,
  Customer,
  Product,
  ServiceItem,
  Category,
  Unit,
  SalesPerson,
  Invoice,
  Payment,
  AuditLog,
  getDefaultPermissions,
} from '../types';
import { calculateInvoiceSummary } from './calculation';

export const initialCompany: CompanySetting = {
  name: 'CV. MIZA MEDIATAMA',
  tagline: 'KOMPUTER – ELEKTRONIK – FURNITUR – PERDAGANGAN UMUM',
  logoUrl: '', // Can be uploaded dynamically
  address: 'Senggotan No 241B RT 09',
  rtRw: 'RT 09',
  village: 'Tirtonirmolo',
  district: 'Kasihan',
  city: 'Bantul',
  province: 'D.I. Yogyakarta',
  postalCode: '55181',
  npwp: '0815712294543000',
  phone: '085643212500',
  email: 'cv.mizamediatama@gmail.com',
  website: 'https://mizamediatama.co.id',
  bankAccounts: [
    {
      id: 'bank-1',
      bankName: 'Bank BCA',
      accountNumber: '037-389-2110',
      accountHolder: 'CV. MIZA MEDIATAMA',
      branch: 'KCP Bantul',
      isDefault: true,
    },
    {
      id: 'bank-2',
      bankName: 'Bank Mandiri',
      accountNumber: '137-00-1928374-1',
      accountHolder: 'CV. MIZA MEDIATAMA',
      branch: 'KC Yogyakarta Sudirman',
      isDefault: false,
    },
    {
      id: 'bank-3',
      bankName: 'Bank BPD DIY',
      accountNumber: '005-211-009876',
      accountHolder: 'CV. MIZA MEDIATAMA',
      branch: 'Cabang Bantul',
      isDefault: false,
    },
  ],
};

export const initialInvoiceSetting: InvoiceSetting = {
  numberFormat: 'INV/{YEAR}/{MONTH}/{SEQ}',
  prefix: 'INV',
  seqPadding: 4,
  resetFrequency: 'monthly',
  defaultDueDays: 14,
  isPpnActive: true,
  ppnRate: 11,
  isMateraiActive: false,
  materaiAmount: 10000,
  materaiThreshold: 5000000,
  defaultNotes: 'Pembayaran dianggap sah apabila telah ditransfer ke rekening resmi CV. MIZA MEDIATAMA dan mengirimkan bukti transfer.',
  defaultTerms: '1. Barang yang sudah dibeli tidak dapat ditukar/dikembalikan kecuali ada perjanjian garansi.\n2. Keterlambatan pembayaran setelah jatuh tempo akan dikenakan konfirmasi berkala.\n3. Pembayaran via Bilyet Giro/Cek baru dianggap lunas setelah kliring.',
  signatoryCustomerTitle: 'Penerima / Pelanggan',
  signatorySalesTitle: 'Hormat Kami (Sales/Marketing)',
  signatoryFinanceTitle: 'Mengetahui (Pimpinan / Keuangan)',
  defaultSignatorySalesName: 'Budi Prasetyo, S.Kom',
  defaultSignatoryFinanceName: 'Ahmad Miza, S.T.',
};

export const initialUsers: User[] = [
  {
    id: 'user-admin',
    username: 'admin',
    name: 'Administrator Miza',
    email: 'admin@mizamediatama.com',
    password: 'admin',
    role: 'admin',
    permissions: getDefaultPermissions('admin'),
    phone: '085643212500',
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    lastLogin: '2026-08-27T08:30:00Z',
  },
  {
    id: 'user-operator',
    username: 'operator',
    name: 'Staff Administrasi & Billing',
    email: 'operator@mizamediatama.com',
    password: 'operator',
    role: 'operator',
    permissions: getDefaultPermissions('operator'),
    phone: '081298765432',
    isActive: true,
    createdAt: '2026-01-15T09:00:00Z',
    lastLogin: '2026-08-26T14:15:00Z',
  },
  {
    id: 'user-manager',
    username: 'manager',
    name: 'Manager Keuangan & Operasional',
    email: 'manager@mizamediatama.com',
    password: 'manager',
    role: 'manager',
    permissions: getDefaultPermissions('manager'),
    phone: '081322334455',
    isActive: true,
    createdAt: '2026-01-10T10:00:00Z',
    lastLogin: '2026-08-27T07:45:00Z',
  },
];

export const initialCategories: Category[] = [
  { id: 'cat-1', code: 'KAT-IT', name: 'Komputer, IT & Hardware', description: 'Perangkat komputer, laptop, server, dan printer', isActive: true },
  { id: 'cat-2', code: 'KAT-MULTIMEDIA', name: 'Multimedia & Display', description: 'Smartboard, proyektor, videotron, sound system', isActive: true },
  { id: 'cat-3', code: 'KAT-PERCETAKAN', name: 'Percetakan & Offset', description: 'Buku, modul ajar, brosur, banner, kalender', isActive: true },
  { id: 'cat-4', code: 'KAT-ATK', name: 'Alat Tulis Kantor & Kertas', description: 'Kertas HVS, tinta, binder, map kantor', isActive: true },
  { id: 'cat-5', code: 'KAT-JASA', name: 'Jasa & Layanan Profesional', description: 'Instalasi, maintenance, perbaikan, desain, pelatihan', isActive: true },
];

export const initialUnits: Unit[] = [
  { id: 'u-1', code: 'pcs', name: 'Pcs' },
  { id: 'u-2', code: 'unit', name: 'Unit' },
  { id: 'u-3', code: 'set', name: 'Set' },
  { id: 'u-4', code: 'paket', name: 'Paket' },
  { id: 'u-5', code: 'box', name: 'Box' },
  { id: 'u-6', code: 'rim', name: 'Rim' },
  { id: 'u-7', code: 'meter', name: 'Meter' },
  { id: 'u-8', code: 'jam', name: 'Jam' },
  { id: 'u-9', code: 'hari', name: 'Hari' },
  { id: 'u-10', code: 'bulan', name: 'Bulan' },
];

export const initialSales: SalesPerson[] = [
  {
    id: 'sales-1',
    code: 'SLS-01',
    name: 'Budi Prasetyo, S.Kom',
    phone: '081234567890',
    email: 'budi.sales@mizamediatama.com',
    address: 'Jl. Bantul Km 7, Kasihan, Bantul',
    commissionRate: 3.5,
    isActive: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'sales-2',
    code: 'SLS-02',
    name: 'Maya Anggraeni, S.E.',
    phone: '085712345678',
    email: 'maya.sales@mizamediatama.com',
    address: 'Jl. Ringroad Selatan, Yogyakarta',
    commissionRate: 4.0,
    isActive: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'sales-3',
    code: 'SLS-03',
    name: 'Deni Setiawan, A.Md.',
    phone: '081898765432',
    email: 'deni.marketing@mizamediatama.com',
    address: 'Jl. Wates Km 4, Gamping, Sleman',
    commissionRate: 3.0,
    isActive: true,
    createdAt: '2026-03-01',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    code: 'CUST-001',
    name: 'Drs. Hendra Supriyadi, M.Pd',
    companyName: 'Dinas Pendidikan Kepemudaan dan Olahraga Kab. Bantul',
    address: 'Komplek Perkantoran Pemkab Bantul, Jl. Lingkar Timur, Manding',
    city: 'Bantul',
    province: 'D.I. Yogyakarta',
    postalCode: '55711',
    npwp: '001234567543000',
    phone: '0274-367509',
    email: 'dikpora@bantulkab.go.id',
    contactPerson: 'Bpk. Hendra (PPK)',
    notes: 'Pelanggan instansi pemerintah, pembayaran via SP2D/Transfer Bank BPD DIY.',
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'cust-2',
    code: 'CUST-002',
    name: 'Rian Pratama, S.T.',
    companyName: 'PT. Graha Digital Solusindo',
    address: 'Jl. Palagan Tentara Pelajar No. 88, Sariharjo, Ngaglik',
    city: 'Sleman',
    province: 'D.I. Yogyakarta',
    postalCode: '55581',
    npwp: '019876543542000',
    phone: '081299887766',
    email: 'finance@grahadigital.co.id',
    contactPerson: 'Ibu Ratna (Finance)',
    notes: 'Partner proyek hardware dan server IT.',
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'cust-3',
    code: 'CUST-003',
    name: 'Ir. Bambang Wijaya',
    companyName: 'Universitas Teknologi Mandiri Yogyakarta',
    address: 'Jl. Glagahsari No. 45, Umbulharjo',
    city: 'Yogyakarta',
    province: 'D.I. Yogyakarta',
    postalCode: '55164',
    npwp: '023344556541000',
    phone: '0274-567890',
    email: 'pengadaan@utm.ac.id',
    contactPerson: 'Bpk. Bambang (Bag. Sarpras)',
    notes: 'Pengadaan modul lab komputer dan multimedia kampus.',
    isActive: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'cust-4',
    code: 'CUST-004',
    name: 'Siti Nurhaliza, S.E.',
    companyName: 'CV. Karya Mandiri Sejahtera',
    address: 'Jl. Kusumanegara No. 112',
    city: 'Yogyakarta',
    province: 'D.I. Yogyakarta',
    postalCode: '55165',
    npwp: '034455667544000',
    phone: '087766554433',
    email: 'karyamandiri.yk@gmail.com',
    contactPerson: 'Ibu Siti',
    notes: 'Cetak kalender tahunan dan buku panduan kerja.',
    isActive: true,
    createdAt: '2026-04-12',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    code: 'PRD-LPT-01',
    sku: 'ASUS-VB14-I5',
    name: 'Laptop ASUS Vivobook 14 (Core i5 / 16GB / 512GB SSD)',
    categoryId: 'cat-1',
    categoryName: 'Komputer, IT & Hardware',
    unit: 'unit',
    costPrice: 8200000,
    sellingPrice: 9750000,
    description: 'RAM 16 GB DDR4, SSD 512 GB NVMe, Layar 14 inch FHD IPS, Windows 11 Home Original + OHS. Garansi Resmi ASUS 2 Tahun.',
    isActive: true,
    createdAt: '2026-01-10',
  },
  {
    id: 'prod-2',
    code: 'PRD-PRN-01',
    sku: 'EPSON-L3210',
    name: 'Printer Epson EcoTank L3210 All-in-One Ink Tank',
    categoryId: 'cat-1',
    categoryName: 'Komputer, IT & Hardware',
    unit: 'unit',
    costPrice: 2050000,
    sellingPrice: 2450000,
    description: 'Print, Scan, Copy. Kecepatan cetak hingga 10 ipm hitam / 5.0 ipm warna. Resolusi 5760 x 1440 dpi. Garansi Resmi Epson 2 Tahun / 30.000 lembar.',
    isActive: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'prod-3',
    code: 'PRD-DS-01',
    sku: 'IFP-HISENSE-65',
    name: 'Interactive Flat Panel Hisense 65 Inch 4K UHD',
    categoryId: 'cat-2',
    categoryName: 'Multimedia & Display',
    unit: 'unit',
    costPrice: 24000000,
    sellingPrice: 28500000,
    description: 'Smart Interactive Board 65" 4K UHD, Multi-touch 20 titik, Built-in Camera & Mic Array, Android 13 + Windows OPS Ready. Termasuk Wall Bracket & Stylus Pen.',
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'prod-4',
    code: 'PRD-PRT-01',
    sku: 'BOOK-MODUL-A4',
    name: 'Cetak Buku Modul Pelatihan A4 Full Color',
    categoryId: 'cat-3',
    categoryName: 'Percetakan & Offset',
    unit: 'exp',
    costPrice: 28000,
    sellingPrice: 45000,
    description: 'Cover Art Carton 260gr Laminasi Doff + Spot UV. Isi HVS 80gr 120 halaman, Jilid Lem Panas (Perfect Binding) + Wrapping Plastik.',
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'prod-5',
    code: 'PRD-ATK-01',
    sku: 'PAP-SIDU-A4-80',
    name: 'Kertas HVS Sinar Dunia (SiDU) A4 80gr (Box isi 5 Rim)',
    categoryId: 'cat-4',
    categoryName: 'Alat Tulis Kantor & Kertas',
    unit: 'box',
    costPrice: 215000,
    sellingPrice: 260000,
    description: 'Kertas HVS Premium A4 (210 x 297 mm) 80 GSM, 1 Box = 5 Rim (2.500 lembar). Kertas putih bersih derajat putih 98%.',
    isActive: true,
    createdAt: '2026-02-15',
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 'srv-1',
    code: 'SRV-NET-01',
    name: 'Jasa Instalasi & Konfigurasi Jaringan LAN / WiFi Kantor',
    description: 'Penarikan kabel UTP Cat6, terminasi patch panel & modular jack, konfigurasi Router MikroTik / Switch Managed, setup SSID WiFi & Bandwidth Management.',
    price: 3500000,
    unit: 'paket',
    isActive: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'srv-2',
    code: 'SRV-SRV-01',
    name: 'Jasa Setup & Maintenance Server Linux / Database',
    description: 'Instalasi OS Linux Server (Ubuntu/Debian), konfigurasi Web Server Nginx/Apache, PostgreSQL/MySQL, SSL Certificate, Automated Backup script & monitoring.',
    price: 4500000,
    unit: 'paket',
    isActive: true,
    createdAt: '2026-02-05',
  },
  {
    id: 'srv-3',
    code: 'SRV-DSG-01',
    name: 'Jasa Desain Grafis & Layout Buku Profil Perusahaan / Kalender',
    description: 'Pembuatan konsep layout, editing visual high-resolution, revisi hingga 3 kali, siap cetak (file master PDF/AI CMYK 300 DPI).',
    price: 1800000,
    unit: 'paket',
    isActive: true,
    createdAt: '2026-02-18',
  },
  {
    id: 'srv-4',
    code: 'SRV-MTC-01',
    name: 'Jasa Service & Perawatan Komputer / Laptop Terjadwal',
    description: 'Pembersihan debu hardware, ganti thermal paste berkualitas, optimasi sistem operasi, pemindaian virus, dan backup data kerja.',
    price: 250000,
    unit: 'unit',
    isActive: true,
    createdAt: '2026-03-01',
  },
];

// Helper to assemble sample invoices with accurate calculation
export function generateInitialInvoices(): { invoices: Invoice[]; payments: Payment[] } {
  const cust1 = initialCustomers[0]; // Dikpora Bantul
  const cust2 = initialCustomers[1]; // Graha Digital
  const cust3 = initialCustomers[2]; // UTM
  const cust4 = initialCustomers[3]; // Karya Mandiri

  const sales1 = initialSales[0];
  const sales2 = initialSales[1];

  const bankDefault = initialCompany.bankAccounts[0];

  // 1. INVOICE 1: INV/2026/08/0001 (PAID)
  const items1 = [
    {
      id: 'item-1-1',
      itemType: 'product' as const,
      itemId: initialProducts[0].id,
      code: initialProducts[0].code,
      name: initialProducts[0].name,
      description: initialProducts[0].description || '',
      quantity: 2,
      unit: 'unit',
      costPrice: 8200000,
      totalCost: 16400000,
      unitPrice: 9750000,
      discountType: 'nominal' as const,
      discountValue: 250000,
      discountAmount: 250000,
      isTaxable: true,
      totalPrice: (2 * 9750000) - 250000, // 19.250.000
    },
    {
      id: 'item-1-2',
      itemType: 'service' as const,
      itemId: initialServices[0].id,
      code: initialServices[0].code,
      name: initialServices[0].name,
      description: initialServices[0].description || '',
      quantity: 1,
      unit: 'paket',
      costPrice: 1200000,
      totalCost: 1200000,
      unitPrice: 3500000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 3500000,
    },
  ];

  const calc1 = calculateInvoiceSummary({
    items: items1,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 0,
    isPpnActive: true,
    ppnRate: 11,
    isMateraiActive: true,
    materaiAmount: 10000,
    amountPaid: 25267500,
  });

  const inv1: Invoice = {
    id: 'inv-2026-08-0001',
    invoiceNumber: 'INV/2026/08/0001',
    poNumber: 'PO/DIKPORA/2026/08/019',
    invoiceDate: '2026-08-05',
    deliveryDate: '2026-08-08',
    dueDate: '2026-08-19',
    customerId: cust1.id,
    customerSnapshot: cust1,
    salesId: sales1.id,
    salesSnapshot: sales1,
    salesChannel: 'Tender Instansi',
    items: items1,
    subtotal: calc1.subtotal,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 0,
    invoiceDiscountAmount: 0,
    taxableBase: calc1.taxableBase,
    isPpnActive: true,
    ppnRate: 11,
    ppnAmount: calc1.ppnAmount,
    isMateraiActive: true,
    materaiAmount: 10000,
    grandTotal: calc1.grandTotal,
    amountPaid: calc1.grandTotal,
    remainingBalance: 0,
    terbilang: calc1.terbilang,
    notes: 'Pengadaan peralatan IT Laboratorium Pendidikan Tahun Anggaran 2026.',
    terms: initialInvoiceSetting.defaultTerms,
    bankAccountId: bankDefault.id,
    bankAccountSnapshot: bankDefault,
    signatoryCustomerName: cust1.name,
    signatorySalesName: sales1.name,
    signatoryFinanceName: 'Ahmad Miza, S.T.',
    status: 'paid',
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-12T14:30:00Z',
    createdByUserId: 'user-admin',
    createdByName: 'Administrator Miza',
  };

  const payment1: Payment = {
    id: 'pay-2026-08-0001',
    paymentNumber: 'PAY/2026/08/0001',
    invoiceId: inv1.id,
    invoiceNumber: inv1.invoiceNumber,
    customerId: cust1.id,
    customerName: cust1.companyName,
    paymentDate: '2026-08-12',
    amount: calc1.grandTotal,
    paymentMethod: 'Transfer Bank',
    bankAccountId: bankDefault.id,
    bankAccountInfo: `${bankDefault.bankName} - ${bankDefault.accountNumber}`,
    referenceNumber: 'SP2D-BANTUL-89421',
    notes: 'Pelunasan SP2D termin 100% dari Bank BPD DIY ke Rekening BCA.',
    createdAt: '2026-08-12T14:30:00Z',
    createdByUserId: 'user-admin',
    createdByName: 'Administrator Miza',
  };

  // 2. INVOICE 2: INV/2026/08/0002 (PARTIAL PAYMENT)
  const items2 = [
    {
      id: 'item-2-1',
      itemType: 'product' as const,
      itemId: initialProducts[2].id,
      code: initialProducts[2].code,
      name: initialProducts[2].name,
      description: initialProducts[2].description || '',
      quantity: 1,
      unit: 'unit',
      costPrice: 24000000,
      totalCost: 24000000,
      unitPrice: 28500000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 28500000,
    },
    {
      id: 'item-2-2',
      itemType: 'product' as const,
      itemId: initialProducts[1].id,
      code: initialProducts[1].code,
      name: initialProducts[1].name,
      description: initialProducts[1].description || '',
      quantity: 2,
      unit: 'unit',
      costPrice: 2050000,
      totalCost: 4100000,
      unitPrice: 2450000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 4900000,
    },
  ];

  const calc2 = calculateInvoiceSummary({
    items: items2,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 400000,
    isPpnActive: true,
    ppnRate: 11,
    isMateraiActive: true,
    materaiAmount: 10000,
    amountPaid: 15000000,
  });

  const inv2: Invoice = {
    id: 'inv-2026-08-0002',
    invoiceNumber: 'INV/2026/08/0002',
    poNumber: 'PO-GDS-AUG-042',
    invoiceDate: '2026-08-15',
    deliveryDate: '2026-08-18',
    dueDate: '2026-08-29',
    customerId: cust2.id,
    customerSnapshot: cust2,
    salesId: sales2.id,
    salesSnapshot: sales2,
    salesChannel: 'Project B2B',
    items: items2,
    subtotal: calc2.subtotal,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 400000,
    invoiceDiscountAmount: 400000,
    taxableBase: calc2.taxableBase,
    isPpnActive: true,
    ppnRate: 11,
    ppnAmount: calc2.ppnAmount,
    isMateraiActive: true,
    materaiAmount: 10000,
    grandTotal: calc2.grandTotal,
    amountPaid: 15000000,
    remainingBalance: calc2.grandTotal - 15000000,
    terbilang: calc2.terbilang,
    notes: 'Pembayaran DP 40% telah diterima. Sisa dibayarkan maksimal tanggal 29 Agustus 2026.',
    terms: initialInvoiceSetting.defaultTerms,
    bankAccountId: bankDefault.id,
    bankAccountSnapshot: bankDefault,
    signatoryCustomerName: cust2.name,
    signatorySalesName: sales2.name,
    signatoryFinanceName: 'Ahmad Miza, S.T.',
    status: 'partial',
    createdAt: '2026-08-15T10:30:00Z',
    updatedAt: '2026-08-16T11:00:00Z',
    createdByUserId: 'user-operator',
    createdByName: 'Staff Administrasi & Billing',
  };

  const payment2: Payment = {
    id: 'pay-2026-08-0002',
    paymentNumber: 'PAY/2026/08/0002',
    invoiceId: inv2.id,
    invoiceNumber: inv2.invoiceNumber,
    customerId: cust2.id,
    customerName: cust2.companyName,
    paymentDate: '2026-08-16',
    amount: 15000000,
    paymentMethod: 'Transfer Bank',
    bankAccountId: bankDefault.id,
    bankAccountInfo: `${bankDefault.bankName} - ${bankDefault.accountNumber}`,
    referenceNumber: 'TRF-MBCA-9812401',
    notes: 'Pembayaran Uang Muka (DP) Pengadaan Smartboard & Printer.',
    createdAt: '2026-08-16T11:00:00Z',
    createdByUserId: 'user-operator',
    createdByName: 'Staff Administrasi & Billing',
  };

  // 3. INVOICE 3: INV/2026/08/0003 (SENT / UNPAID)
  const items3 = [
    {
      id: 'item-3-1',
      itemType: 'product' as const,
      itemId: initialProducts[3].id,
      code: initialProducts[3].code,
      name: initialProducts[3].name,
      description: initialProducts[3].description || '',
      quantity: 300,
      unit: 'exp',
      costPrice: 28000,
      totalCost: 300 * 28000,
      unitPrice: 45000,
      discountType: 'percentage' as const,
      discountValue: 5,
      discountAmount: 675000,
      isTaxable: true,
      totalPrice: (300 * 45000) - 675000, // 12.825.000
    },
    {
      id: 'item-3-2',
      itemType: 'service' as const,
      itemId: initialServices[2].id,
      code: initialServices[2].code,
      name: initialServices[2].name,
      description: initialServices[2].description || '',
      quantity: 1,
      unit: 'paket',
      costPrice: 600000,
      totalCost: 600000,
      unitPrice: 1800000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 1800000,
    },
  ];

  const calc3 = calculateInvoiceSummary({
    items: items3,
    invoiceDiscountType: 'percentage',
    invoiceDiscountValue: 0,
    isPpnActive: true,
    ppnRate: 11,
    isMateraiActive: true,
    materaiAmount: 10000,
    amountPaid: 0,
  });

  const inv3: Invoice = {
    id: 'inv-2026-08-0003',
    invoiceNumber: 'INV/2026/08/0003',
    poNumber: 'PO-UTM-2026-088',
    invoiceDate: '2026-08-20',
    deliveryDate: '2026-08-25',
    dueDate: '2026-09-03',
    customerId: cust3.id,
    customerSnapshot: cust3,
    salesId: sales1.id,
    salesSnapshot: sales1,
    salesChannel: 'Direct B2B',
    items: items3,
    subtotal: calc3.subtotal,
    invoiceDiscountType: 'percentage',
    invoiceDiscountValue: 0,
    invoiceDiscountAmount: 0,
    taxableBase: calc3.taxableBase,
    isPpnActive: true,
    ppnRate: 11,
    ppnAmount: calc3.ppnAmount,
    isMateraiActive: true,
    materaiAmount: 10000,
    grandTotal: calc3.grandTotal,
    amountPaid: 0,
    remainingBalance: calc3.grandTotal,
    terbilang: calc3.terbilang,
    notes: 'Pengadaan modul materi kuliah semester ganjil 2026/2027.',
    terms: initialInvoiceSetting.defaultTerms,
    bankAccountId: bankDefault.id,
    bankAccountSnapshot: bankDefault,
    signatoryCustomerName: cust3.name,
    signatorySalesName: sales1.name,
    signatoryFinanceName: 'Ahmad Miza, S.T.',
    status: 'sent',
    createdAt: '2026-08-20T13:40:00Z',
    updatedAt: '2026-08-20T13:40:00Z',
    createdByUserId: 'user-admin',
    createdByName: 'Administrator Miza',
  };

  // 4. INVOICE 4: INV/2026/07/0014 (OVERDUE)
  const items4 = [
    {
      id: 'item-4-1',
      itemType: 'product' as const,
      itemId: initialProducts[4].id,
      code: initialProducts[4].code,
      name: initialProducts[4].name,
      description: initialProducts[4].description || '',
      quantity: 15,
      unit: 'box',
      costPrice: 210000,
      totalCost: 15 * 210000,
      unitPrice: 260000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 3900000,
    },
    {
      id: 'item-4-2',
      itemType: 'service' as const,
      itemId: initialServices[3].id,
      code: initialServices[3].code,
      name: initialServices[3].name,
      description: initialServices[3].description || '',
      quantity: 4,
      unit: 'unit',
      costPrice: 80000,
      totalCost: 4 * 80000,
      unitPrice: 250000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 1000000,
    },
  ];

  const calc4 = calculateInvoiceSummary({
    items: items4,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 0,
    isPpnActive: true,
    ppnRate: 11,
    isMateraiActive: false,
    materaiAmount: 10000,
    amountPaid: 0,
  });

  const inv4: Invoice = {
    id: 'inv-2026-07-0014',
    invoiceNumber: 'INV/2026/07/0014',
    poNumber: 'PO-KMS-0711',
    invoiceDate: '2026-07-10',
    deliveryDate: '2026-07-12',
    dueDate: '2026-07-24', // Past due date!
    customerId: cust4.id,
    customerSnapshot: cust4,
    salesId: sales2.id,
    salesSnapshot: sales2,
    salesChannel: 'Direct',
    items: items4,
    subtotal: calc4.subtotal,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 0,
    invoiceDiscountAmount: 0,
    taxableBase: calc4.taxableBase,
    isPpnActive: true,
    ppnRate: 11,
    ppnAmount: calc4.ppnAmount,
    isMateraiActive: false,
    materaiAmount: 0,
    grandTotal: calc4.grandTotal,
    amountPaid: 0,
    remainingBalance: calc4.grandTotal,
    terbilang: calc4.terbilang,
    notes: 'Pengadaan kertas kantor & jasa perawatan PC bulanan.',
    terms: initialInvoiceSetting.defaultTerms,
    bankAccountId: bankDefault.id,
    bankAccountSnapshot: bankDefault,
    signatoryCustomerName: cust4.name,
    signatorySalesName: sales2.name,
    signatoryFinanceName: 'Ahmad Miza, S.T.',
    status: 'overdue',
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-10T11:00:00Z',
    createdByUserId: 'user-admin',
    createdByName: 'Administrator Miza',
  };

  // 5. INVOICE 5: INV/2026/08/0004 (DRAFT)
  const items5 = [
    {
      id: 'item-5-1',
      itemType: 'service' as const,
      itemId: initialServices[1].id,
      code: initialServices[1].code,
      name: initialServices[1].name,
      description: initialServices[1].description || '',
      quantity: 1,
      unit: 'paket',
      costPrice: 1500000,
      totalCost: 1500000,
      unitPrice: 4500000,
      discountType: 'percentage' as const,
      discountValue: 0,
      discountAmount: 0,
      isTaxable: true,
      totalPrice: 4500000,
    },
  ];

  const calc5 = calculateInvoiceSummary({
    items: items5,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 0,
    isPpnActive: true,
    ppnRate: 11,
    isMateraiActive: false,
    materaiAmount: 0,
    amountPaid: 0,
  });

  const inv5: Invoice = {
    id: 'inv-2026-08-0004',
    invoiceNumber: 'INV/2026/08/0004',
    poNumber: 'DRAFT-PROJECT-SERVER',
    invoiceDate: '2026-08-27',
    deliveryDate: '2026-08-30',
    dueDate: '2026-09-10',
    customerId: cust2.id,
    customerSnapshot: cust2,
    salesId: sales1.id,
    salesSnapshot: sales1,
    salesChannel: 'Project B2B',
    items: items5,
    subtotal: calc5.subtotal,
    invoiceDiscountType: 'nominal',
    invoiceDiscountValue: 0,
    invoiceDiscountAmount: 0,
    taxableBase: calc5.taxableBase,
    isPpnActive: true,
    ppnRate: 11,
    ppnAmount: calc5.ppnAmount,
    isMateraiActive: false,
    materaiAmount: 0,
    grandTotal: calc5.grandTotal,
    amountPaid: 0,
    remainingBalance: calc5.grandTotal,
    terbilang: calc5.terbilang,
    notes: 'Draft penawaran & invoice instalasi cloud VPS & Database PostgreSQL.',
    terms: initialInvoiceSetting.defaultTerms,
    bankAccountId: bankDefault.id,
    bankAccountSnapshot: bankDefault,
    signatoryCustomerName: cust2.name,
    signatorySalesName: sales1.name,
    signatoryFinanceName: 'Ahmad Miza, S.T.',
    status: 'draft',
    createdAt: '2026-08-27T07:15:00Z',
    updatedAt: '2026-08-27T07:15:00Z',
    createdByUserId: 'user-operator',
    createdByName: 'Staff Administrasi & Billing',
  };

  return {
    invoices: [inv1, inv2, inv3, inv4, inv5],
    payments: [payment1, payment2],
  };
}

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-08-27T08:30:00Z',
    userId: 'user-admin',
    userName: 'Administrator Miza',
    userRole: 'admin',
    action: 'LOGIN',
    module: 'AUTH',
    details: 'Berhasil login ke sistem melalui Web Dashboard.',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-20T13:40:00Z',
    userId: 'user-admin',
    userName: 'Administrator Miza',
    userRole: 'admin',
    action: 'CREATE_INVOICE',
    module: 'INVOICE',
    recordId: 'inv-2026-08-0003',
    recordIdentifier: 'INV/2026/08/0003',
    details: 'Menerbitkan invoice baru untuk Universitas Teknologi Mandiri Yogyakarta senilai Rp 16.230.750.',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-16T11:00:00Z',
    userId: 'user-operator',
    userName: 'Staff Administrasi & Billing',
    userRole: 'operator',
    action: 'RECORD_PAYMENT',
    module: 'PAYMENT',
    recordId: 'pay-2026-08-0002',
    recordIdentifier: 'PAY/2026/08/0002',
    details: 'Mencatat pembayaran uang muka (DP) senilai Rp 15.000.000 untuk invoice INV/2026/08/0002.',
    ipAddress: '192.168.1.105',
  },
  {
    id: 'log-4',
    timestamp: '2026-08-12T14:30:00Z',
    userId: 'user-admin',
    userName: 'Administrator Miza',
    userRole: 'admin',
    action: 'RECORD_PAYMENT',
    module: 'PAYMENT',
    recordId: 'pay-2026-08-0001',
    recordIdentifier: 'PAY/2026/08/0001',
    details: 'Mencatat pelunasan invoice INV/2026/08/0001 senilai Rp 25.267.500 dari Dinas Pendidikan Kab. Bantul.',
    ipAddress: '192.168.1.100',
  },
];
